# Generated by Django 6.0.2 on 2026-02-04 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('date', models.DateTimeField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.cities')),
            ],
        ),
    ]
